feat: update to `nightly-2025-12-15`
Remove reference to rustc_hash due to error:

> error[E0464]: multiple candidates for rmeta dependency rustc_hash found